on:
  workflow_run:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
    workflows:
      - .github/workflows/main.yml
    types:
      - completed

jobs:
  post-main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "post-main"

  pre-commit-autoupdate:
    uses: ./.github/workflows/_pre-commit-autoupdate.yml
    permissions:
      contents: write
      pull-requests: write

  pdm-publish:
    uses: ./.github/workflows/_pdm-publish.yml
    permissions:
      contents: read
      id-token: write
